### PR TITLE
fix(tracing): normalize incoming trace/span IDs from upstream tracers

### LINKED ISSUE #833: [Bug]: Got Exception ,Only supported hex string lengths are 16 and 32
### Problem Description

We are using instana agent for our nodejs application. The agent throws exception time to time as following.  The exception happening when the application try to send a message via kafka, due to exception some of the message sending operations fails. Our expectation is the instana agent should not break the application internal operations.  We already tried to upgrade the latest version unfortunately we are still facing with exception.

`Only supported hex string lengths are 16 and 32, got: 1521f334c97fd3d[39m
Error: Only supported hex string lengths are 16 and 32, got: 1521f334c97fd3d
    at Object.unsignedHexStringToBuffer (/src/node_modules/@instana/core/src/tracing/tracingUtil.js:111:11)
    at Object.unsignedHexStringsToBuffer (/src/node_modules/@instana/core/src/tracing/tracingUtil.js:124:11)
    at Object.renderTraceContextToBuffer (/src/node_modules/@instana/core/src/tracing/tracingUtil.js:153:18)
    at addLegacyTraceContextHeaderToAllMessages (/src/node_modules/@instana/core/src/tracing/instrumentation/messaging/kafkaJs.js:452:23)
    at addTraceContextHeaderToAllMessages (/src/node_modules/@instana/core/src/tracing/instrumentation/messaging/kafkaJs.js:437:7)
    at /src/node_modules/@instana/core/src/tracing/instrumentation/messaging/kafkaJs.js:94:7
    at /src/node_modules/@instana/core/src/tracing/clsHooked/async_local_storage_context.js:161:15
    at /src/node_modules/@instana/core/src/tracing/clsHooked/async_local_storage_context.js:148:32
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Namespace.run (/src/node_modules/@instana/core/src/tracing/clsHooked/async_local_storage_context.js:148:13)`

### Short, Self Contained Example

```
    try {
            await this.kafka.send({ topic: topic }, order, order?.dcid, {
                dcid: order.dcid,
            });
            this.logger.log(`PushOrderToQueue dc-order-api successfully queued item to ${topic} dcId: ${order?.dcid}`);
        } catch (error) {
            this.logger.error(`PushOrderToQueue error updating status: ${error} TopicName: ${topic} DcId: ${order?.dcid}`);
        }
```

### Node.js Version

v18.16.1

### package.json

```shell
{
  "name": "dc-api-service-order",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json",
    "sonar": "sonar-scanner"
  },
  "dependencies": {
    "@instana/collector": "^2.27.0",
    "@nestjs/axios": "^1.0.1",
    "@nestjs/common": "9.3.9",
    "@nestjs/config": "2.3.1",
    "@nestjs/core": "9.3.9",
    "@nestjs/microservices": "9.3.9",
    "@nestjs/mongoose": "9.2.1",
    "@nestjs/passport": "^9.0.3",
    "@nestjs/platform-express": "9.3.9",
    "@nestjs/swagger": "6.2.1",
    "@type-cacheable/core": "11.0.1",
    "@type-cacheable/ioredis-adapter": "12.1.0",
    "agentkeepalive": "^4.3.0",
    "fast-xml-parser": "3.18.0",
    "he": "1.2.0",
    "ioredis": "^5.3.1",
    "kafkajs": "^1.16.0",
    "mongoose": "6.9.2",
    "passport": "^0.6.0",
    "passport-headerapikey": "^1.2.2",
    "reflect-metadata": "^0.1.13",
    "request-ip": "^3.3.0",
    "rxjs": "^7.8.0",
    "soap": "^1.0.0",
    "swagger-ui-express": "4.6.0",
    "uuid": "^9.0.0",
    "xml2js": "^0.4.23"
  },
  "devDependencies": {
    "@nestjs/cli": "9.2.0",
    "@nestjs/schematics": "9.0.4",
    "@nestjs/testing": "9.3.9",
    "@types/express": "4.17.17",
    "@types/jest": "29.4.0",
    "@types/node": "18.13.0",
    "@types/superagent": "4.1.16",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.52.0",
    "@typescript-eslint/parser": "^5.52.0",
    "eslint": "^8.34.0",
    "eslint-config-prettier": "8.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.4.3",
    "prettier": "^2.8.4",
    "sonar-scanner": "^3.1.0",
    "supertest": "^6.3.3",
    "ts-jest": "^29.0.5",
    "ts-loader": "^9.4.2",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.1.2",
    "typescript": "^4.9.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### package-lock.json

```shell
{}
```

### PR DESCRIPTION
**Pull request by basti1302**
When an incoming trace correlation ID (trace ID or span ID) is shorter than the standard length, we now normalize it by left-padding it with "0" characters.

Additionally, do not throw an error in tracingUtil, instead simply log
an error.

Fixes:
```
Only supported hex string lengths are 16 and 32, got: ...
at Object.unsignedHexStringToBuffer (node_modules/@instana/core/src/tracing/tracingUtil.js:111:11)
at Object.unsignedHexStringsToBuffer (node_modules/@instana/core/src/tracing/tracingUtil.js:124:11)
at Object.renderTraceContextToBuffer (node_modules/@instana/core/src/tracing/tracingUtil.js:153:18)
at addLegacyTraceContextHeaderToAllMessages (node_modules/@instana/core/src/tracing/instrumentation/messaging/kafkaJs.js:452:23)
```

fixes #833

### CODE REVIEW

File: packages/core/src/tracing/cls.js [hunk 1]
```diff
@@ -282,9 +283,15 @@ function startSpan(spanName, kind, traceId, parentSpanId, w3cTraceContext) {
 
   // If the client code has specified a trace ID/parent ID, use the provided IDs.
   if (traceId) {
-    span.t = traceId;
+    // The incoming trace ID/span ID from an upstream tracer could be shorter than the standard length. Some of our code
+    // (in particular, the binary Kafka trace correlation header X_INSTANA_C) assumes the standard length. We normalize
+    // both IDs here by left-padding with 0 characters.
+
+    // Maintenance note (128-bit-trace-ids): When we switch to 128 bit trace IDs, we need to left-pad the trace ID to 32
```
Comment (basti1302) [inline packages/core/src/tracing/cls.js:290]: Not directly related to the issue at hand, but I added a couple of those comments with a common identifier that can be searched for easily (128-bit-trace-ids), in all places I could think of that need to be updated when we switch from 64 bit trace IDs to 128 bit trace IDs.

File: packages/core/src/tracing/cls.js [hunk 2]
```diff
@@ -282,9 +283,15 @@ function startSpan(spanName, kind, traceId, parentSpanId, w3cTraceContext) {
...
+    // characters instead of 16.
+    span.t = leftPad(traceId, 16);
```
Comment (basti1302) [inline packages/core/src/tracing/cls.js:292]: The left pad here (and the one two lines below) are the actual fix.

Comment (kirrg001) [reply packages/core/src/tracing/cls.js:292]: Question: Was wondering if there is a case that the incoming traceID is longer than 16.

Comment (basti1302) [reply packages/core/src/tracing/cls.js:292]: Good question.

Yes, there are cases, in particular 128 bit trace IDs, which are 32 characters long. Being able to correctly handle 128 bit trace IDs correctly is an important part of our strategy for migrating to that length. See https://www.notion.so/instana/Migration-To-128-Bit-Trace-IDs-e5a6615416f645f792f5dec96d3e2896 for our internal docs on that. At the moment, no Instana tracer will send a 128 bit trace ID via HTTP etc., but at some point that will change, and of course we need to make sure that our tracers of today are already capable of handling that correctly.

Most of that is handled in https://github.com/instana/nodejs/blob/main/packages/core/src/tracing/tracingHeaders.js#L364-L370.

However, now that you have brought it up, I think there are two cases we might want to think about:
* The `tracingHeaders.limitTraceId` function checks for length >= 32. Trace IDs with a length > 16 and < 32 will not be limited. (I don't think these occur out in the wild but well, you never know.)
* Not every incoming trace ID goes through `tracingHeaders.limitTraceId`. For example, for grpcJs.

These are definitely things we should check on. I lean towards doing that in a different PR, and focussing on trace IDs shorter than 16 characters in this PR.

**Comment by basti1302** [comment]
Looks like this broke a couple test cases, I'll need to look into that.

**Review by aryamohanan — APPROVED** [review]
